### PR TITLE
Allow memory index to access arbitrary data

### PR DESCRIPTION
**Pull request by jcorbin**
Could go even further and introduce json-able type checking here, along the lines of:
```typescript
type JSONAtom = null | number | string | boolean
type JSONValue = JSONAtom | JSONValue[] | Object<string, JSONValue>
```

### Brief Description

{Please write here}

### Checklists

- [ ] Test passed
- [ ] Coding style (indentation, etc)
- [ ] Edits have been made to `src/` files not `index.d.ts`
- [ ] Run `npm run dtslint` to update `index.d.ts`

### CODE REVIEW

**Comment by jcorbin** [comment]
Hmm, I totally missed the readme section about this... interesting...

**Comment by pyrodogg** [comment]
Unfortunately, this is a one-way street, so to speak. It's possible to add an index signature through interface merging, but it is not possible to remove or override one once added. Merging this would thus prevent users from having strictly typed memory without tampering with the `@types/screeps` files directly.

Having untyped, or more loosely typed memory is definitely a valid player choice but it's not a good fit to bake in here due to the limitations of Typescript. You can add these signatures to your own project as outlined in the readme.

**Comment by jcorbin** [comment]
That makes sense, and on balance I now really like the nudge towards strongly typed memory; I think my only concerns remain as:
- type checking is all well and good, but there's nothing stopping the operator (say at the in-game console) from mutating a part of memory into something that breaks such type assumptions
- READMEs are all well and good, but how about some comment guidance for easier discovery in-editor ( e.g. jump after jumping to type definition shortly after starting to typecheck a pre-existing script )
- I so far have an unresolved `Cannot redeclare block-scoped variable 'Memory'` error that I've `// @ts-ignore`ed my way past for now

I'll hold off on any further PRs until I actually get through getting my script to pass typechecking with these definitions.

**Comment by pyrodogg** [comment]
Have you noticed the `screeps-typescript-starter project`? It's a good resource for people new to Typescript. It has an example for how to add additional properties to the 'core' interfaces in the main.ts file without having tots-ignore anything.  I also recommend the #typescript channel on the Screeps slack server, good community for answering questions about TS in Screeps.

**Pull request closed without merging**
