### PR TITLE
Add some overloads

### PR DESCRIPTION
**Pull request by Arcath**
Overloads some of the functions to remove the need to type the output.

With the current system, you had to type the output of some functions e.g.

```ts
room.find<Creep>(FIND_MY_CREEPS) // Has the type Creep[]
```

But come along later and change the find to something else

```ts
room.find<Creep>(FIND_MY_SPAWNS) // Still has the type Creep[]
```

Overloads let us change the output if the input has various types

```ts
room.find(FIND_MY_CREEPS) // Creep[]
room.find(FIND_MY_SPAWNS) // StructureSpawn[]
```

The old method is still supported and is there for anything that doesn't match the overloads.

There are more methods that could be overloaded so please don't pull this yet.

### CODE REVIEW

**Comment by Arcath** [comment]
The last commit adds a `test` command that should let us know when things get broken.

`npm test` runs:

1. `npm run compile`
1. `npm run lint`
1. `npm run compile-test`

If the lint fails or either typescript compiles fail the tests will fail. @resir014 You can enable TravisCI after this PR is pulled to get automated testing up and running if you think its worth it.

**Comment by Arcath** [comment]
There's a little issue with jsdoc to fix now then its good to do.

the documentation only applies to the first overload, leaving the rest un documented.

**Comment by resir014** [comment]
@Arcath Thanks for looking into the docblocks as well! Really appreciate it.

**Comment by Arcath** [comment]
@resir014 It should be good to pull now. Might want to test it against your own AI first but it should be good to go.

**Comment by Arcath** [comment]
Some discussion on slack has made some overloading un needed. I'm working on it now.

**Comment by Arcath** [comment]
The latest commit actually removes most of my overloads in favour of some pretty crafty generic typing.

I'm not sure how backwards compatible this code is now.

**Comment by resir014** [comment]
@Arcath Hm, okay. I'll take a look at this tomorrow and test against my own code if possible.

I'll probably be on Slack tomorrow to discuss whether or not we'll do a major version bump.

**Pull request merged**
