### PR TITLE
Add ERR_NAME_EXISTS to index.d.ts ScreepsReturnCode definition

### PR DESCRIPTION
**Pull request by caleywoods**
### Brief Description

This fixes an issue I was encountering trying to compare a return code from `.spawnCreep()` to the constant `ERR_NAME_EXISTS` or to the number value of `-3`.

The code I had in question that was failing prior to this fix was:
```
let creepAttempt = Game.spawns['Spawn1'].spawnCreep([WORK, CARRY, MOVE], 'Harvester1', {
  memory: { role: 'harvester' }
});

if ( creepAttempt === ERR_NAME_EXISTS ) {
  // creep name already exists - try to get a new name
}
```

The TS compiler (transpiler?) was returning an error that Operator `===` cannot be applied to types 'ScreepsReturnCode` and `-3`

### Checklists

- [x] Test passed
- [x] Coding style (indentation, etc)

### CODE REVIEW

**Comment by Arcath** [comment]
`index.d.ts` is generated when we compile from the `src` folder. Could you apply your changes to `src/literals.ts` instead? Otherwise, they will get overwritten next time we compile anything.

**Comment by caleywoods** [comment]
@Arcath Thanks for the heads up! I went ahead and reverted the `.d.ts` file change and fixed `src/literals.ts`. I wasn't aware there was a compilation step, the more you know. 🤜

**Comment by caleywoods** [comment]
@resir014 Thanks for pulling that new contributing markdown file into there, you beat me to it! Glad I could help out with this. Have a good day.

**Comment by resir014** [comment]
@caleywoods No problem. Thanks for your PR!

**Pull request merged**
