### PR TITLE
DT Support

### PR DESCRIPTION
**Pull request by Arcath**
### Brief Description

Restructure for DT.

Replaces our linter config with the dtlint config. Moves tests into the dist folder. Changes compile to concat so that `tsc` doesn't mess with line lengths etc...

### Checklists

- [x] Test passed
- [x] Coding style (indentation, etc)

### CODE REVIEW

**Comment by Arcath** [comment]
The Memory interfaces are causing a problem at the moment.

Shall I define the index signature? will that work how we want?

**Comment by Arcath** [comment]
Current linter errors:

```
ERROR: 1:1      dt-header                        Header should only be in `index.d.ts`. See: https://github.com/Microsoft/dtslint/blob/master/docs/dt-header.md
ERROR: 10:1     dt-header                        TypeScript version should be specified under header in `index.d.ts`. See: https://github.com/Microsoft/dtslint/blob/master/docs/dt-header.md
ERROR: 2055:11  no-empty-interface               An empty interface is equivalent to `{}`.
ERROR: 2056:11  no-empty-interface               An empty interface is equivalent to `{}`.
ERROR: 2057:11  no-empty-interface               An empty interface is equivalent to `{}`.
ERROR: 2058:11  no-empty-interface               An empty interface is equivalent to `{}`.
ERROR: 3800:1   strict-export-declare-modifiers  'declare' keyword is redundant here. See: https://github.com/Microsoft/dtslint/blob/master/docs/strict-export-declare-modifiers.md
ERROR: 3819:1   strict-export-declare-modifiers  'declare' keyword is redundant here. See: https://github.com/Microsoft/dtslint/blob/master/docs/strict-export-declare-modifiers.md
```

**Comment by resir014** [comment]
@Arcath 

> Shall I define the index signature? will that work how we want?

Typing them using the index signatures might work, but we might just move the problem back a stage where if someone wants to include another interface inside of it, still not sure if it plays well w/ a type of `{ [key: string]: any }`

We could create some test cases for that, I guess.

**Comment by Arcath** [comment]
I've disabled a couple of rules that were causing problems.

 - `no-redundant-jsdoc-2` as per https://github.com/palantir/tslint/issues/3413
 - `dt-header` was causing problems that shouldn't apply when we actually push to dt.
 - `no-empty-interface`  we **do** need to define an empty interface that can be overwritten later.

Tests fail now but I wonder if we need to run `tsc` anymore. `dtslint` seems to pick up on compile errors.

**Pull request merged**
